exclude: '^(?!App/).*$'
repos:
-   repo: https://github.com/realm/SwiftLint
    rev: 0.50.3
    hooks:
    -   id: swiftlint
-   repo: https://github.com/calda/SwiftFormat
    rev: 0.55-beta-13
    hooks:
    -   id: swiftformat